trigger:
  branches:
    include:
    - FOR_PIPELINE
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  
 - script: |
    pip install pytest requests setuptools wheel
    pip install -U databricks-cli
  displayName: 'Load Python Dependencies'

- script: |
    databricks fs cp ... dbfs:/...
  env:
    DATABRICKS_HOST: $(https://adb-6192355565634015.15.azuredatabricks.net/)
    DATABRICKS_TOKEN: $(dapi238b624ec6a89bda46554dd0e6769cb5)
  displayName: 'Copy artifacts'