trigger:
  branches:
    include:
    - FOR_PIPELINE
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: configuredatabricks@0
    displayName: Configure Databricks CLI
    inputs:
      url: $(https://adb-6192355565634015.15.azuredatabricks.net/)
      token: $(dapi238b624ec6a89bda46554dd0e6769cb5)
  

